ALTER TABLE `user_genre`
  DROP FOREIGN KEY `FK_USER_GENRE_USER`,
  DROP FOREIGN KEY `FK_USER_GENRE_GENRE`;

ALTER TABLE `discussion`
  DROP FOREIGN KEY `FK_DISCUSSION_USER_ID`,
  DROP FOREIGN KEY `FK_DISCUSSION_BOOK_ID`;

ALTER TABLE `quote_like`
  DROP FOREIGN KEY `FK_QUOTE_LIKE_QUOTE`,
  DROP FOREIGN KEY `FK_QUOTE_LIKE_USER`;

ALTER TABLE `discussion_comment`
  DROP FOREIGN KEY `FK_COMMENT_DISCUSSION`,
  DROP FOREIGN KEY `FK_COMMENT_USER`;

ALTER TABLE `bookmark`
  DROP FOREIGN KEY `FK_BOOKMARK_BOOK`,
  DROP FOREIGN KEY `FK_BOOKMARK_USER`;

ALTER TABLE `book_genre`
  DROP FOREIGN KEY `FK_BOOK_GENRE_GENRE`,
  DROP FOREIGN KEY `FK_BOOK_GENRE_BOOK`;

ALTER TABLE `vote`
  DROP FOREIGN KEY `FK_VOTE_USER`,
  DROP FOREIGN KEY `FK_VOTE_DISCUSSION`;

ALTER TABLE `discussion_like`
  DROP FOREIGN KEY `FK_DISCUSSION_LIKE_USER`,
  DROP FOREIGN KEY `FK_DISCUSSION_LIKE_DISCUSSION`;

ALTER TABLE `quote`
  DROP FOREIGN KEY `FK_QUOTE_USER`,
  DROP FOREIGN KEY `FK_QUOTE_BOOK`;


DROP TABLE IF EXISTS `user_genre`;
DROP TABLE IF EXISTS `book_genre`;
DROP TABLE IF EXISTS `bookmark`;
DROP TABLE IF EXISTS `quote_like`;
DROP TABLE IF EXISTS `discussion_like`;
DROP TABLE IF EXISTS `vote`;
DROP TABLE IF EXISTS `discussion_comment`;
DROP TABLE IF EXISTS `quote`;
DROP TABLE IF EXISTS `discussion`;
DROP TABLE IF EXISTS `book`;
DROP TABLE IF EXISTS `genre`;
DROP TABLE IF EXISTS `user`;
