-- created_at 필드 자동 생성 설정 및 user 테이블 nickname 수정
ALTER TABLE `user`
MODIFY COLUMN `nickname` VARCHAR(100) NULL COMMENT '닉네임';

ALTER TABLE `user`
MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `discussion`
MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `quote`
MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `discussion_comment`
MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;